require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rubycw
  - rubocop-rake
  - rubocop-performance

Style/AsciiComments:
  Enabled: false
  Description: this service is for Jap.

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 33

Rails/HelperInstanceVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
